# Generated by Django 6.0.1 on 2026-01-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_status_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
        ),
    ]
